version: "3.7"
services:
  backend:
    build: backend
    secrets:
      - db-password
    ports:
      - 5000:5000
  db:
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    image: mysql:8.0.19
    restart: always
    secrets:
    - db-password
    volumes:
    - db-data:/var/lib/mysql
  proxy:
    build: proxy
    ports:
    - 8080:80
volumes:
  db-data: {}
secrets:
  db-password:
    file: db/password.txt
